const alarmSystem = require('./lib/alarmSystem');

const {
    ACTIVATE_TOPIC,
    FALSE_POSITIVES_HANDLING,
    SEND_MESSAGE_ON_SUSPICIOUS_STATE,
    MIN_SENSORS_QUANTITY_TO_ALARM,
    MAX_INVOCATION_TIME_DIFF,
    ACTIVATE_MESSAGE,
    DEACTIVATE_MESSAGE,
    SENSOR_TOPIC,
    SENSOR_MESSAGE,
    ACTION_TOPIC,
    NOTIFICATION_CHANNELS,
    SEND_SYSTEM_ARMING_MESSAGE,
    SEND_SYSTEM_DISARMING_MESSAGE,
    SEND_PANIC_MESSAGE
} = scenario.args;

alarmSystem(
    ACTIVATE_TOPIC,
    ACTIVATE_MESSAGE,
    DEACTIVATE_MESSAGE,
    SENSOR_TOPIC,
    SENSOR_MESSAGE,
    ACTION_TOPIC,
    NOTIFICATION_CHANNELS,
    SEND_SYSTEM_ARMING_MESSAGE,
    SEND_SYSTEM_DISARMING_MESSAGE,
    SEND_PANIC_MESSAGE,
    FALSE_POSITIVES_HANDLING,
    SEND_MESSAGE_ON_SUSPICIOUS_STATE,
    MIN_SENSORS_QUANTITY_TO_ALARM,
    MAX_INVOCATION_TIME_DIFF,
);
